#!/bin/bash

# API ENDPOINTS
echo "#https://artifactory.papermc.io/ui/native/universe/io/papermc/paper/paper-api/"
echo "https://artifactory.papermc.io/artifactory/universe/io/papermc/paper/paper-api/1.21.9-rc1-R0.1-SNAPSHOT/"


wget https://artifactory.papermc.io/artifactory/universe/io/papermc/paper/paper-api/26.1.2.build.9-alpha/paper-api-26.1.2.build.9-alpha-javadoc.jaR

mv *.jar jar_apis/
